version: "3.8"
services:

  chat-management-app:
    hostname: backend
    restart: on-failure
    image: chat-management-app
    container_name: chat-management-container
    build: ./
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=local-docker
    networks:
      - demo_net
networks:
  demo_net:
      external: true
